apiVersion: v1
kind: Service
metadata:
  name: epwatcher
spec:
  ports:
  - port: 62000
    protocol: TCP
    nodePort: 30000
  selector:
    app: epwatcher
  type: NodePort

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: default                                                                                                                         
  labels:                                                                                                          
    app: epwatcher
  name: epwatcher
spec:
  selector:
    matchLabels:
      app: epwatcher
  template:
    metadata:
      labels:
        app: epwatcher
    spec:
      containers:
      - image: ratnadeepb/epwatcher:latest
        name: epwatcher
        ports:
        - containerPort: 62000
      serviceAccountName: epwatcher-accnt