apiVersion: v1
kind: Service
metadata:
  name: epwatcher
spec:
  ports:
  - port: 62000
    nodePort: 30000
    protocol: TCP
  selector:
    app: epwatcher
  type: NodePort

---

apiVersion: apps/v1
kind: DaemonSet
metadata:                                                                                                                                           
  labels:                                                                                                                                                                                                   
    app: epwatcher
  name: epwatcher
spec:
  selector:
    matchLabels:
      app: epwatcher
  template:
    metadata:
      labels:
        app: epwatcher
    spec:
      containers:
      - image: ratnadeepb/epwatcher:latest
        name: epwatcher
        ports:
        - containerPort: 62000