apiVersion: apps/v1
kind: DaemonSet
metadata:
  # namespace: micocontrol                                                                                                                         
  labels:                                                                                                                                                                                                   
    app: epwatcher
  name: epwatcher
spec:
  selector:
    matchLabels:
      app: epwatcher
  template:
    metadata:
      labels:
        app: epwatcher
    spec:
      containers:
      - image: ratnadeepb/epwatcher:latest
        name: epwatcher
        ports:
        - containerPort: 62000
          hostPort: 62000
      serviceAccountName: epwatcher-accnt