apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: epwatcher-role
  # namespace: micocontrol
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
    resources:
      - pods
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: epwatcher-accnt
  # namespace: micocontrol

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mico-rolebinding
  # namespace: micocontrol
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: epwatcher-role
subjects:
- namespace: micocontrol 
  kind: ServiceAccount
  name: epwatcher-accnt